//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Notifications
    {
        public int NotificationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BroadCastId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_LiveBroadCast tbl_LiveBroadCast { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
