//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Logs
    {
        public int LogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Operation { get; set; }
        public string ErrorDescription { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreadedBy { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
