//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Markers
    {
        public int LocationId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
