//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Room
    {
        public int RoomId { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Token { get; set; }
        public string VideoCategory { get; set; }
        public string Latitude { get; set; }
        public string longitude { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> TokenIssueDate { get; set; }
        public Nullable<System.DateTime> TokenExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
