//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NearByUser
    {
        public int Id { get; set; }
        public string PublisherSessionId { get; set; }
        public string PublisherToken { get; set; }
        public string SubscriberToken { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ArchiveId { get; set; }
        public Nullable<int> roomJoinedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> roomCreatedUserId { get; set; }
        public string VideoURL { get; set; }
        public string VideoCategory { get; set; }
    }
}
