//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LiveBroadCast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LiveBroadCast()
        {
            this.tbl_Notifications = new HashSet<tbl_Notifications>();
        }
    
        public int BroadCastId { get; set; }
        public Nullable<int> VideoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BroadCastLimit { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
        public virtual tbl_VideoCategories tbl_VideoCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Notifications> tbl_Notifications { get; set; }
    }
}
